version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11.0
    container_name: 'rabbitmq-docker-image'
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
        - ~/data/:/var/lib/rabbitmq/
        - ~/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge